config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :edit, :update, :destroy]
  root 'projects#index'

  resources :projects, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:new]
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'session/login', to: 'sessions#new'
  post 'session/login', to: 'sessions#create'
  delete 'session/logout', to: 'sessions#destroy'

  resources :users
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :project_categories
  has_many :projects, through: :project_categories

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  #belongs_to :user

  scope :most_recent, -> (limit) { order("created_at desc").limit(limit) }

  validates :description, presence: true

  

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_categories
  has_many :categories, through: :project_categories
  belongs_to :user, optional: true
  has_many :comments

  validates :title, presence: true
  validates :description, presence: true

  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      if !category_attribute[:name].blank?
        category = Category.find_or_create_by(category_attribute)
        self.categories << category
      end
    end
  end

end

app/models/project_category.rb
class ProjectCategory < ApplicationRecord
  belongs_to :project
  belongs_to :category

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :projects
  has_many :comments, through: :projects

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, presence: true

  def self.find_or_create_by_omniauth(auth_hash)
    self.where(username: auth_hash['info']['name']).first_or_create do |user|
   # Specify the data you’re looking for. If it exists in the table, the first instance will be returned. If not, then create is called.

      user.password = SecureRandom.hex
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def authentication_required
    if !logged_in?
      redirect_to login_path
    end
  end

  def logged_in?
    session[:user_id] 
  end

  def current_user
    User.find(session[:user_id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new(project_id: params[:project_id])
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      @comment.user_id = current_user.id
      @comment.save
      redirect_to project_path(@comment.project_id)
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.user_id == current_user.id
      @comment.update(comment_params)
      @comment.user_id = current_user.id
      @comment.save
      redirect_to project_path(@comment.project_id)
    else
      redirect_to project_path(@comment.project_id), notice: 'You are not authorized to edit or delete this comment'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user_id == current_user.id
      @comment.destroy
      redirect_to project_path(@comment.project_id)
    else
      redirect_to project_path(@comment.project_id), notice: 'You are not authorized to edit or delete this comment'
    end 
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :project_id, :user_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      @project.user_id = current_user.id
      @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
    @project = find_project
    @project_comments = @project.comments.most_recent(@project.comments.count)
  end

  def edit
    @project = find_project
  end

  def update
    @project = find_project
    if current_user
      @project.update(project_params)
      redirect_to project_path
    else
      flash[:notice] = "You are not authorized to edit this project"
      redirect to edit_project_path
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, category_ids:[], categories_attributes: [:name])
  end

  def find_project
    Project.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if auth_hash = request.env['omniauth.auth']
      user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = user.id
      redirect_to root_path, notice: ', you are signed in'
    else

      @user = User.find_by(username: params[:username])

      if !@user
        flash[:warning] = "Please check you information, and try again"
        redirect_to root_path
      elsif
        @user.authenticate(params[:password])
        user_id = @user.id
        session[:user_id] = user_id
        redirect_to root_path, notice: ', you are signed in'
      else
        flash[:alert] = "Incorrect password"
        render :new
      end
    end

  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      user_id = @user.id
      session[:user_id] = user_id
      redirect_to root_path, notice: ', you are signed in'
    else
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/show.html.erb
<div class="container">
  <p style="color:red">Category Show Page</p>
</div>

<div class="container">
  <%= @category.name %>:
</div>

<div class="container">
  <% @category.projects.each do |project| %>
   | <%= link_to project.title, project_path(project) %>
  <% end %>
</div>

app/views/comments/_errors.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <p style="color:red">
      <%= pluralize(@comment.errors.count, "error") %>
      prohibited this comment from being saved:
    </p>

    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="container">
    <%= f.hidden_field :project_id %>
    <%= f.text_area :description %>
    <%= f.submit %>

</div>

app/views/comments/edit.html.erb
<% if @comment.errors.any? %>
<div class="container">
  <%= render 'errors' %>
</div>
<% end %>

<div class="container">
  <p style="color:red">Edit your comment</p>
  <%= bootstrap_form_for(@comment) do |f| %>
      <%= render 'form', f: f %>
  <% end %>
</div>

app/views/comments/new.html.erb
<div class="container">
  <%= render 'errors' %>
</div>

<div class="container">
  <p style="color:red">Contribute a Comment to DYI</p>
  <%= bootstrap_form_for(@comment) do |f| %>
      <%= render 'form', f: f %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<!-- signin/signup if user is not logged in-->
<% if session[:user_id].present? %>
  <li class="nav-item"><%= link_to 'Sign out |', session_logout_path, method: 'DELETE', class: 'nav-link' %></li>
  <li class="nav-item"><%= link_to 'Contribute your project to DYI |', new_project_path, class: 'nav-link' %></li>
<% else %>
  <li class="nav-item"><%= link_to 'Sign up |', new_user_path, class: 'nav-link' %></li>
  <li class="nav-item"><%= link_to 'Sign in |', session_login_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DYI App</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">

      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a style="color:green"class="nav-link" href="/">DYI HOME |<span class="sr-only">(current)</span></a>
            </li>

            <!-- signin/signup if user is not logged in-->
            <%= render 'layouts/navbar' %>

          </ul>
        </div>
      </nav>
    </nav> <!-- end of 'class="navbar navbar-light"'-->

    <% if logged_in? %>
      <div class="container">
        <h4>Welcome, <%= current_user.username %> <%= flash[:notice]%></h4>
      </div>
    <% end %>


    <%= yield %>

      <!-- jQuery first, then Tether, then Bootstrap JS. -->
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

app/views/projects/_errors.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <p style="color:red">
      <%= pluralize(@project.errors.count, "error") %>
      prohibited this comment from being saved:
    </p>

    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/projects/_form.html.erb
<div class="container">

    <%= f.text_field :title %>
    <%= f.text_area :description %>

    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>

    <%= f.fields_for :categories, @project.categories.build do |categories_fields| %>
      <%= f.label "Category:" %>
      <%= categories_fields.text_field :name %>
    <% end %>

    <%= f.submit %>

</div>

app/views/projects/_show.html.erb
<div class="container">
  <%= flash[:warning] %>
</div>
__________________________________________________________________________________________________________________________________________________________

<p style="display:inline; font-weight:bold;">Categories:</p><% @project.categories.each do |category| %> |
  <%= link_to category.name, category_path(category) %>
<% end %>
<br></br>

<p style="display:inline; font-weight:bold;">Title:</p> <%= @project.title %><br></br>
<p style="display:inline; font-weight:bold;">Description:</p> <%= @project.description %><br></br>

  <% if @project.user_id == current_user.id %>
      <%= link_to 'Edit', edit_project_path %> | <%= link_to "Delete", @project, method: :delete, data: { confirm: "WAIT! Seriously?" } %>
  <% end %>

__________________________________________________________________________________________________________________________________________________________

<!-- validation erros, move to partial-->

<%= link_to "New Comment", new_project_comment_path(@project) %>
<p style="font-weight:bold;">Comments:</p>
<% @project_comments.each do |comment| %>
  <div class="container" style="border : solid 2px #ff0000; color:blue; padding : 4px; width : 800px; height : 200px; overflow : auto; ">
      <h2 style="color:red"><%= flash[:notice] %></h2>
   ~> <%= comment.description %><br>

       <%= link_to 'Edit', edit_comment_path(comment) %> | <%= link_to "Delete", comment, method: :delete, data: { confirm: "WAIT! Seriously?" } %>

 </div><br>
<% end %>

app/views/projects/edit.html.erb
<%= flash[:notice] %>
<div class="container">
  <p style="color:red">Edit your DYI project</p>
  <%= bootstrap_form_for(@project) do |f| %>
      <%= render 'form', f: f %>
  <% end %>
</div>

app/views/projects/index.html.erb
<!-- this needs to be put in a partial -->
<div class="container">
  <p style="color:blue"><%= flash[:warning] %></p>
</div>


<div class="container">
  <p style="color:red" >Search projects by category:</p>
  <% Category.all.each do |category| %> |
    <% if logged_in? %>
      <%= link_to category.name, category_path(category) %>
    <% else %>
      <%= category.name %>
    <% end %>
  <% end %>
</div>

<!-- this needs to be put in a partial -->
<div class="container">
  __________________________________________________________________________________________________________________________________________________________
</div>

<div class="container">
  <p style="color:red">List of Projects:</p>
  <% @projects.each do |project| %>
    <% if logged_in? %>
      <p><%= link_to project.title, project_path(project) %></p>
    <% else %>
      <p><%= project.title %></p>
    <% end %>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="container">
  <%= render 'errors' %>
</div>

<div class="container">
  <p style="color:red">Contribute to DYI</p>
  <%= bootstrap_form_for(@project) do |f| %>
      <%= render 'form', f: f %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <p style="color:red">Project Show Page</p>
  <%= render 'show' %>
</div>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <p style="color:red">
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this project from being saved:
    </p>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <%= render 'errors' %>
</div>
<div class="container">
  <p style="color:red">Sign up:</p>
  <%= bootstrap_form_for(@user) do |f| %>
    <%= f.text_field :username %>
    <%= f.text_field :email %>
    <%= f.password_field :password %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit 'Sign up'%>
  <% end %>
</div>